City-Bureau/city-scrapers

README.md
=> update readme with dummy text

docs/contribute-a-spider.md, documenters_aggregator/settings.py, requirements.txt, tasks.py, templates/spider.tmpl, templates/test.tmpl, tests/files/test_testspider.py.example, tests/files/testspider.py.example, tests/test_tasks.py, tests/utils.py
=> invoke genspider + some tests

docs/contribute-a-spider.md, docs/installation.md
=> clean up installation docs a bit

tests/test_tasks.py
=> just test page title in genspider test generation

documenters_aggregator/spiders/cdph.py, tests/files/cdph.html, tests/test_cdph.py
I think this one should be good to go.
=> SPIDER: Chicago Department of Public Health Board

tasks.py
Our intermittent test failures are the result of the citybureau.org
server returning a 429 response when a test attempts to fetch some
HTML. In an effort to make our tests solidly green and remove the
intermittent failures, this commit adds retrying functionality to the
_gen_html function. We retry up to 5 times, with an exponentially increasing
backoff (2, 4, 8, 16, 32 seconds).
Please note that this is a temporary fix, as ultimately we should not be hitting
the network to run these tests. I can think of two solutions:
1. Have two test suites, one for local unit tests and one that tests
remote systems.
2. Use a library to mock out these requests so we don't rely on the
network.
In the short term, however, I think this fix will improve the experience
for new developers.
=> Retry attempts to fetch a URL.

LICENSE, documenters_aggregator/middlewares.py, documenters_aggregator/settings.py
=> 0053 disable robotstxt

docs/code-of-conduct.md
from https://docs.google.com/document/d/1GEwPPpdhFEZnf9xEgJm1PXYfznMbiTaPM3XWTLIEdrA/edit
closes #40
=> add Contributor Covenant Code of Conduct

docs/faq.md
This gives us a place to put frequently asked questions. Addresses #77 and completes #49.
=> Add FAQ file.

documenters_aggregator/spiders/ilrb.py, requirements.txt, tests/files/ilrb.html, tests/test_ilrb.py
This is a completed spider and test (#82) for the [Illinois Labor Relation Board events page](https://www.illinois.gov/ilrb/meetings/Pages/default.aspx).  It's a simple page that just lists the next upcoming meeting for each of the three boards.
There's little structure on the page to work with, so the scraper may be a bit fragile.
Questions:
- How do we handle undefined end_times? Set to None or estimate a duration
- I could use some more guidance on classification. It seems like this page only lists confirmed meetings, but most of the other scrapers default to tentative
- Is there a taxonomy of meeting types? I set these to "board meeting", but I can change it to None
=> 82 SPIDER Illinois Labor Relations Board

documenters_aggregator/spiders/cceb.py, tests/files/cceb_default.html, tests/test_cceb.py
=> SPIDER: cook county elections board - working spider

documenters_aggregator/spiders/cpb.py, tests/files/cpb_public_meetings.html, tests/test_cpb.py
=> 0103 spider cpb

tasks.py, templates/spider.tmpl, templates/test.tmpl, tests/files/test_testspider.py.example, tests/files/testspider.py.example, tests/test_tasks.py
I ran into some errors and failing tests that can be fixed in the templates.
=> Template updates

documenters_aggregator/pipelines.py
=> prettier logging pipeline output

documenters_aggregator/spiders/caps.py, tests/test_caps.py
=> clean up caps scraper

deploy/prod_settings.py.example, documenters_aggregator/settings.py
=> clean up user_agent strings

documenters_aggregator/spiders/cchhs.py, documenters_aggregator/spiders/cclba.py, documenters_aggregator/spiders/cdph.py, documenters_aggregator/spiders/cit.py, documenters_aggregator/spiders/cpl.py, documenters_aggregator/spiders/ilrb.py, tests/test_cchhs.py, tests/test_cclba.py, tests/test_cdph.py, tests/test_cit.py, tests/test_cpl.py
resolves #133 -- puts all the dates in the same format
=> 0133 fix dates

tests/files/testspider.py.example
Looks like all Travis tests are failing because the typo fixed in #154 was still in the test template. This should fix it
=> Fix test template failures from #154

documenters_aggregator/spiders/accc.py, tests/files/accc.html, tests/test_accc.py
=> SPIDER: Animal Care and Control Commission

docs/SUMMARY.md
should handle #159 but must see for sure after merge
=> add contribute spider back to summary

deploy/prod.sh.example, documenters_aggregator/spider.py, documenters_aggregator/spiders/chi_infra.py, documenters_aggregator/spiders/chi_library.py, documenters_aggregator/spiders/chi_police.py, documenters_aggregator/spiders/chi_pubhealth.py, documenters_aggregator/spiders/cook_board.py, documenters_aggregator/spiders/cook_county.py, documenters_aggregator/spiders/cook_electoral.py, documenters_aggregator/spiders/cook_hospitals.py, documenters_aggregator/spiders/cook_landbank.py, documenters_aggregator/spiders/cook_pubhealth.py, documenters_aggregator/spiders/il_labor.py, documenters_aggregator/spiders/il_pubhealth.py, documenters_aggregator/spiders/regionaltransit.py, documenters_aggregator/spiders/ward_night.py, tests/test_chi_infra.py, tests/test_chi_library.py, tests/test_chi_police.py, tests/test_chi_pubhealth.py, tests/test_cook_board.py, tests/test_cook_electoral.py, tests/test_cook_hospitals.py, tests/test_cook_landbank.py, tests/test_cook_pubhealth.py, tests/test_il_labor.py, tests/test_il_pubhealth.py, tests/test_regionaltransit.py
This set of patches updates the rest of the spiders to use the new standardized ID format.
=> Remaining spiders use standardized IDs

documenters_aggregator/pipelines/airtable.py
=> replace missing values with 'n/a' in airtable pipeline

documenters_aggregator/pipelines/ValidationPipeline.py, documenters_aggregator/pipelines/__init__.py, documenters_aggregator/settings.py
@jim , this validation pipeline is ready for deployment. It will create some new validation fields. Just needs to be added to the ITEM_PIPELINES in prod_settings.py .
resolves #185
=> validation pipeline ready for deployment

docs/event-schema.md, documenters_aggregator/spiders/chi_citycouncil.py, documenters_aggregator/spiders/chi_infra.py, documenters_aggregator/spiders/chi_policeboard.py, tests/test_chi_citycouncil.py, tests/test_cook_pubhealth.py
=> 0221 fix citycouncil times

documenters_aggregator/spiders/chi_school_actions.py, tests/files/chi_school_actions.html, tests/test_chi_school_actions.py
Closes #218. I haven't fully built out the tests since overall it's pretty straightforward, but this covers the CPS School Actions page which looks like it's used across multiple years.
I mention this in a `TODO` comment, but there are multiple links to documents that I didn't see a place to include. I also used the type of meeting as the classification, but not sure if the type of action would be better suited for that
=> Add CPS School action spider

documenters_aggregator/spiders/metra_board.py, tests/files/metra_board.html, tests/test_metra_board.py
Addresses #193. Not much info available for each meeting, I think I populated everything I could.
=> Add Metra Board meeting scraper

documenters_aggregator/spiders/chi_animal.py
fixed  *broken string format error* for chi_animal.py
=> fixed chi_animal date strings

documenters_aggregator/spiders/chi_parks.py
New general description text applies to all chi_parks meetings. I may need to add a line about the board specifically down the line.
=> WIP: update Park District Board of Commissioners description

README.md
Changes the layout of the status table for #265. @diaholliday let me know if this is what you were thinking!
=> Reverse status table order

docs/01_project.md
Fixing the Installation and Contribution links (they were renamed)
=> Fix broken links

docs/prerequisites.md
Adding some additional resources for a first-time development environment setup, with @ckwms63 's help.
=> Creating a prerequisites file

documenters_aggregator/spiders/chi_transit.py, tests/files/chi_transit.html, tests/test_chi_transit.py
Updated start_url with new CTA meetings URL.
=> Update chi_transit scraper with new CTA website

documenters_aggregator/settings.py, documenters_aggregator/spiders/chi_police.py, tests/test_chi_police.py
=> Updated description for chi_police

documenters_aggregator/spiders/regionaltransit.py, tests/test_regionaltransit.py
From issue #275 
The code around the description was a bit different from the other spider I edited, so hopefully this works.
=> Update description in regionaltransit (RTA) spider

city_scrapers/pipelines/localExporter.py
Added additional try/except to localExport to address issues arising from start times with None values
=> WIP: Fixed pipeline start time error

city_scrapers/spiders/il_labor.py
=> #314 www -> www2

city_scrapers/spiders/il_labor.py, tests/files/il_labor.html, tests/test_il_labor.py
- Update to reflect new page layout.
- Fixes #353
=> Update for new page layout

city_scrapers/spiders/chi_boardofethics.py, tests/files/chi_boardofethics.html, tests/test_chi_boardofethics.py
=> New Chicago Board of Ethics Spider 

city_scrapers/spiders/chi_schools.py, tests/test_chi_schools.py
- Update event schema #380
- Replace static description with info at the bottom of the page
- Scrape "participation guidelines" url as a document
=> Update event schema #380

city_scrapers/spiders/chi_ward_night.py, docs/faq.md, tests/test_ward_night.py
- update to reflect new schema
- change spider name to chi_ward_night
=> Update ward_night schema for #380 

city_scrapers/spiders/il_pubhealth.py, tests/test_il_pubhealth.py
=> Update il_pubhealth schema for #380

city_scrapers/spiders/wayne_cow.py, tests/test_wayne_cow.py
- update schema
- replace static description
- scrape documents
=> Update wayne_cow schema for #380

city_scrapers/spiders/cook_county.py, tests/test_cook_county.py, tests/test_il_regional_transit.py
- scrape documents,
- use classification in google sheet
- drop non-governing events like free clinics
=> Update cook_county schema for #380

city_scrapers/spiders/cook_hospitals.py, tests/test_cook_hospitals.py
- update schema
- use classification field to differentiate board and various committee meetings
- remove static description
- scrape documents
=> WIP: update cook_hospitals schema

city_scrapers/mixins/wayne_commission.py, city_scrapers/spiders/wayne_audit.py, tests/files/wayne_audit.html, tests/test_wayne_audit.py
Looking for feedback on the creation of mixins folder. Relates to issue #439
=> WIP - 439 issue mixins classes

city_scrapers/mixins/wayne_commission.py, city_scrapers/spiders/wayne_ways_means.py, tests/files/wayne_ways_means.html, tests/test_wayne_ways_means.py
First pass at wayne_ways_means. Works with mixin wayne_commission. References issue #449
=> 449 spider wayne ways means

city_scrapers/mixins/wayne_commission.py, city_scrapers/spiders/wayne_economic_development.py, city_scrapers/spiders/wayne_government_operations.py, city_scrapers/spiders/wayne_health_human_services.py, city_scrapers/spiders/wayne_public_safety.py, city_scrapers/spiders/wayne_public_services.py, tests/files/wayne_economic-development.html, tests/files/wayne_government-operations.html, tests/files/wayne_health_human_services.html, tests/files/wayne_public-safety.html, tests/files/wayne_public_services.html, tests/test_wayne_economic_development.py, tests/test_wayne_government_operations.py, tests/test_wayne_health_human_services.py, tests/test_wayne_public_safety.py, tests/test_wayne_public_services.py
Aggregate the wayne commission committee spiders which are currently ready. 
This commit supersedes the following PRs: #447 , #445 , #443 , #436 , #426 
Relates to issue #457
=> 457 aggregate currently ready wayne commission spiders and their tests

city_scrapers/spiders/chi_school_community_action_council.py, tests/test_chi_school_community_action_council.py
- removed static descriptions
- added neighborhood websites to sources 
- made sure the tests don't depend on the month that the spider is run
@jim or @bonfirefan , can you double check that the tests for this spider don't depend on the month that it's run?
=> update CAC spider to the new schema

city_scrapers/spiders/chi_parks.py, city_scrapers/spiders/chi_water.py, city_scrapers/spiders/cook_board.py
Updates the creation of `LegistarEventsScraper` to the new parameters now that we're on the most recent version of `python-legistar-scraper`. Merging if the CI passes to un-block #464
=> Update legistar initializers

city_scrapers/spiders/chi_localschoolcouncil.py, tests/test_chi_localschoolcouncil.py
- removes static agency description
- adds estimated end times
- adds community areas to locations
=> update chi_lsc spider to new schema

city_scrapers/spiders/mi_belle_isle.py, tests/files/mi_belle_isle.html, tests/test_mi_belle_isle.py
References issue #478 
Ready for reviews!
=> 478 spider mi belle isle

tests/test_det_eight_mile_woodward_corridor_improvement_authority.py
=> Fixes #499 time dependent failing test

tests/test_det_downtown_development_authority.py, tests/test_det_eight_mile_woodward_corridor_improvement_authority.py, tests/test_det_local_development_finance_authority.py, tests/test_next_michigan_development_corporation.py
@bonfirefan I sorted the test cases for the 4 files that I would expect this issue to affect. Try this pr when you get a minute and see if this resolves the issue that you were having locally #484
=> Sort test items so tests are consistent across environments

city_scrapers/spiders/det_library_commission.py, tests/files/det_library_commission.html, tests/files/det_library_commission_detail.html, tests/test_det_library_commission.py
First pass at Library Commission spider. References #492
=> 492 spider - det_library_commission

city_scrapers/spiders/wayne_election_commission.py, tests/files/wayne_election_commission.html, tests/test_wayne_election_commission.py
In progress - still working on the documents
=> wayne_election_commission

city_scrapers/spiders/chi_animal.py, tests/test_chi_animal.py
Addresses #380.
Paired with @laurieskelly on this at SRCCON.
Moving the discussion here so we don't clutter up the main thread in #380.
=> Update `chi_animal` to new event schema

city_scrapers/spiders/chi_community_development.py, tests/test_chi_community_development.py
Was listing 1am instead of 1pm
=> Fix community development commission time

city_scrapers/spiders/chi_ssa_1.py, city_scrapers/spiders/chi_ssa_14.py, city_scrapers/spiders/chi_ssa_5.py, tasks.py, tests/files/chi_ssa_1.html, tests/files/chi_ssa_14.html, tests/files/chi_ssa_5.html, tests/files/chi_ssa_5_minutes.html, tests/test_chi_ssa_1.py, tests/test_chi_ssa_14.py, tests/test_chi_ssa_5.py
Adds spiders for Special Service Areas 1, 5, and 14 with more to come. Will need to create a new issue for these, since there are around 40 that we could make scrapers for
=> Initial Special Service Area spiders

city_scrapers/spiders/chi_city_college.py, city_scrapers/spiders/chi_police.py, city_scrapers/spiders/det_city_council.py, city_scrapers/spiders/il_metra_board.py
* Fix null errors on `chi_city_college` and `det_city_council`
* Handle invalid response on `chi_police`
* Ignore robots.txt on `il_metra_board` since it forbids the entire site
=> Fix failing scrapers

city_scrapers/spiders/chi_schools.py, city_scrapers/spiders/det_land_bank.py, city_scrapers/spiders/il_regional_transit.py
* Checks that start time list is returned in `chi_schools` before processing
* Updates the xpath for pulling data in `det_land_bank`
* Add a URL scheme if one isn't supplied in `il_regional_transit`
=> Fix errors reported in Sentry

city_scrapers/spiders/det_wrecking_examiners.py, tests/files/det_wrecking_examiners.html, tests/test_det_wrecking_examiners.py
Looks as if city of detroit moved from Dot Net Nuke to Drupal!
This wasn't able to use wayne_mixin.
Mentions #540
=> 539 - Rewrite det_wrecking_examiners

city_scrapers/settings/prod.py, city_scrapers/spiders/chi_city_college.py, city_scrapers/spiders/chi_school_community_action_council.py, city_scrapers/spiders/chi_ssa_14.py, city_scrapers/spiders/chi_teacherpension.py, city_scrapers/spiders/cook_landbank.py, city_scrapers/spiders/det_economic_development_corporation.py, city_scrapers/spiders/mi_belle_isle.py, city_scrapers/spiders/next_michigan_development_corporation.py, deploy/run_scrapers.py, tasks.py
Remove f string literals for Python 3.5 compatibility
=> Remove f string literals

city_scrapers/spiders/il_metra_board.py, tests/test_il_metra_board.py
The Metra site includes minutes, agendas, and video of each meeting, so this pulls those from the archive
=> Pull Metra archive, docs

city_scrapers/spiders/chi_buildings.py, tests/files/chi_buildings.json, tests/test_chi_buildings.py
Fixes a lot of issues with `chi_buildings` including meetings being reported as 12:00am and most meetings being listed as being all day
=> Account for chi_buildings data issues

city_scrapers/spiders/pitt_housing.py, tests/files/pitt_housing_board-info.html, tests/test_pitt_housing.py
This pull request addresses issue #576 , containing a spider that crawls the Housing Authority of the City of Pittsburgh Board of Commisioners meetings page.
Marked as WIP since this is my first PR, but both the spider and test file are complete (and hopefully correct). Let me know if you need me to change anything with the files, format of this PR etc. Thanks!
=> #578 Add pitt_housing spider (WIP)

city_scrapers/spiders/chi_ssa_25.py, tests/files/chi_ssa_25.html, tests/test_chi_ssa_25.py
=> Add SSA #25 scraper

city_scrapers/spiders/chi_housing_authority.py, tests/files/chi_housing_authority_minutes.html, tests/files/chi_housing_authority_notice.html, tests/files/chi_housing_authority_upcoming.html, tests/test_chi_housing_authority.py
Closes #624. Adds CHA scraper, pulling documents for upcoming meeting as well as all archived minutes and other documents
=> Add Chicago Housing Authority scraper

city_scrapers/spiders/chi_citycouncil.py, city_scrapers/spiders/chi_community_development.py, city_scrapers/spiders/chi_development_fund.py, city_scrapers/spiders/chi_landmark_commission.py, city_scrapers/spiders/chi_plan_commission.py, city_scrapers/spiders/chi_policeboard.py, city_scrapers/spiders/chi_teacherpension.py, city_scrapers/spiders/chi_zoning_board.py, city_scrapers/spiders/cook_landbank.py, tests/test_chi_citycouncil.py, tests/test_chi_community_development.py, tests/test_chi_development_fund.py, tests/test_chi_landmark_commission.py, tests/test_chi_plan_commission.py, tests/test_chi_teacherpension.py, tests/test_chi_zoning_board.py
* Cleans up statically-assigned locations
* Fix `chi_policeboard` date assignment
* Fix `cook_landbank` locations
=> Cleanup locations, chi police board, cook land bank

Pipfile.lock, city_scrapers/spiders/alle_county.py, city_scrapers/spiders/chi_parks.py, city_scrapers/spiders/cook_board.py, city_scrapers/spiders/cook_water.py, city_scrapers/spiders/det_water_sewage_department.py, requirements.txt, tests/test_cook_board.py, tests/test_cook_water.py
Update Legistar dependency so it scrapes the right URL for videos, pull videos if available for all Legistar-based scrapers
=> Pull videos from Legistar, update legistar dep

city_scrapers/spiders/chi_schools.py, city_scrapers/spiders/cook_landbank.py, tests/test_chi_schools.py, tests/test_cook_landbank.py
Progress on #582 
- Update documents for `chi_schools`
- Add documents to `cook_landbank`
=> Additional documents

README.md, docs/_docs/04-development.md, docs/_includes/footer.html, docs/_includes/head.html
Closes #683, clarifies the fork setup
=> Remove RSS feed, mention template repo in docs

docs/_docs/04-development.md
Makes the description of `Meeting` items easier to read and adds info on how Scrapy `Item` objects work
=> Clarify documentation on Meeting items

docs/_docs/04-development.md
This is my first time contributing on github. Please let me know if I should have done something different.
I didn't think it made sense to create a separate branch for such a small fix.
=> WIP: Typo fix: "tempalte" to "template" in docs

Pipfile.lock, city_scrapers/pipelines/__init__.py, requirements.txt
Updates core package for improved title string cleaning
=> Update city-scrapers-core to 0.2.3

docs/_docs/04-development.md
Per discussion in https://github.com/City-Bureau/city-scrapers/pull/697#discussion_r261839741, I am suggesting a small change in the [Development doc](https://cityscrapers.org/docs/development/#a-write-parse-methods-in-the-spider).
=> WIP: Clarify the comment in 04-development.md about hardcoding values

city_scrapers/spiders/cook_pace_board.py, tests/files/cook_pace_board.html, tests/test_cook_pace_board.py
@pjsier I think this should be close to done. 
A few questions:
- Is it right to put `end` and `time_notes` as `None` if they're not applicable?
- How comprehensive should my unit tests be? Are what I have good enough? 
Resolves #678.
=> 0678 spider cook pace board

city_scrapers/spiders/cook_medical_examiner.py, tests/files/cook_medical_examiner.html, tests/test_cook_medical_examiner.py
I finished a first version of the spider (@pjsier). Some of the scraping feels too specific to me, specifically how time and location are extracted (lines 27-33).
I'm sure a lot of the scraping could be done more elegantly. Please let me know if something's not the way it should be!
Tests and linting run fine for me.
=> WIP: 0677 spider cook medical examiner

city_scrapers/spiders/det_historic_district.py, tests/files/det_historic_district.html, tests/test_det_historic_district.py
Created the det_historic_district spider and associated tests following
Issue #700's description, city-scrapers' CONTRIBUTING.md file and the det_city_planning
and det_zoning_appeals spiders.
=> WIP 0700 Spider - Detroit Historic District Commission

city_scrapers/spiders/det_human_rights.py, tests/files/det_human_rights.html, tests/test_det_human_rights.py
Created the det_human_rights spider and associated tests per
Issue #699's description.
Note that at the time this spider was created there were no agency_doc_id values, thus an empty list is provided. In the future, when documents are added to the website, the relevant agency_doc_id values need to be added to this list.
=> 0699 Spider - Detroit Human Rights Commission

.travis.yml, city_scrapers/spiders/chi_il_medical_district.py, tests/files/chi_il_medical_district.html, tests/test_chi_il_medical_district.py
=> Add chi_il_medical_district

city_scrapers/spiders/chi_city_college.py, tests/test_chi_city_college.py
Fixes Chicago City Colleges location, updates it to use the current core setup
=> Fix chi_city_college location

city_scrapers/spiders/chi_labor_retirement_fund.py, tests/files/chi_labor_retirement_fund.html, tests/test_chi_labor_retirement_fund.py
I am having trouble getting the title to return correctly.  I have tried several options to pull the data, but I haven't figured it out yet.
=> WIP 0667 spider chi labor retirement fund

city_scrapers/spiders/chi_metro_pier_exposition.py, tests/files/chi_metro_pier_exposition.html, tests/test_chi_metro_pier_exposition.py
=> Add scraper chi_metro_pier_exposition

city_scrapers/spiders/chi_municipal_retirement.py, tests/files/chi_municipal_retirement.html, tests/test_chi_municipal_retirement.py
=> Add chi_municipal_retirement

city_scrapers/spiders/chi_fire_benefit_fund.py, tests/files/chi_fire_benefit_fund.html, tests/test_chi_fire_benefit_fund.py
=> Add chi_fire_benefit_fund

city_scrapers/spiders/il_opioid_response.py, tests/files/il_opioid_response.html, tests/test_il_opioid_response.py
Implements `il_opioid_response` for https://github.com/City-Bureau/city-scrapers/issues/719
I'm ready for a review on this. I'm pulling the meeting agenda and links from the [links URL]( https://www.dhs.state.il.us/page.aspx?item=104682). https://github.com/City-Bureau/city-scrapers/issues/719 mentions [this page](https://www.dhs.state.il.us/page.aspx?item=97186) as the primary URL, which appears to just list the most recent agenda. Let me know if there's anything additional I should be pulling from that page or any feedback in general.
=> 0719 spider il opioid crisis ac

city_scrapers/spiders/cook_pension.py, tests/files/cook_pension.html, tests/test_cook_pension.py
Adds scraper for the Cook County Pension Fund
=> Add cook_pension

city_scrapers/spiders/chi_infrastructure_trust.py, tests/files/chi_infrastructure_trust.html, tests/test_chi_infrastructure_trust.py
Implements https://github.com/City-Bureau/city-scrapers/issues/717
=> 0717 spider chi infrastructure trust

city_scrapers/spiders/chi_plan_commission.py
Ignore failed parsed start times
=> Fix chi_plan_commission

Pipfile.lock, city_scrapers/settings/prod.py
Use Open Civic Data for the final export, doesn't require scraper level updates
=> Update city-scrapers-core, use OCD pipeline

city_scrapers/spiders/chi_police_retirement.py, tests/files/chi_police_retirement.html, tests/test_chi_police_retirement.py
Hi,
I still need to write _parse_documents and tests at the very least but I am having an issue with running the `crawl` command. Specifically: `ERROR: Spider error processing <GET http://www.chipabf.org/ChicagoPolicePension/MonthlyMeetings.html> (referer: None)`
However, when I run `scrapy shell http://www.chipabf.org/ChicagoPolicePension/MonthlyMeetings.html` I get the right response object which is how I wrote the code I currently have. I'm sure the fix is simple just need to be pointed in the right direction.
Finally, can I be added to the slack channel? I filled out the form to be added but haven't received an invite.
=> [WIP] initial commit for 0674-chi_police_retirement

city_scrapers/spiders/il_gaming_board.py, tests/files/il_gaming_board.html, tests/test_il_gaming_board.py
=> Add il_gaming_board spider

city_scrapers/spiders/chi_ssa_73.py, tests/files/chi_ssa_73.html, tests/test_chi_ssa_73.py
This is my first spider.  I think it's good to go, but I welcome feedback.
=> 0570 spider chi ssa73

city_scrapers/mixins/__init__.py, city_scrapers/mixins/chi_mayors_advisory_councils.py, city_scrapers/spiders/chi_mayors_bicycle_advisory_council.py, city_scrapers/spiders/chi_mayors_pedestrian_advisory_council.py, tests/files/chi_mayors_pedestrian_advisory_council.html, tests/test_chi_mayors_pedestrian_advisory_council.py
Closes #387, reuses functionality from the bicycle advisory council
=> Refactor mayor's advisory councils, add pedestrian

city_scrapers/spiders/chi_ssa_34.py, tests/files/chi_ssa_34.html, tests/test_chi_ssa_34.py
=> Add chi_ssa_34

city_scrapers/spiders/chi_ssa_26.py, tests/files/chi_ssa_26.html, tests/test_chi_ssa_26.py
=> Add chi_ssa_26

city_scrapers/mixins/__init__.py, city_scrapers/mixins/chi_rogers_park_ssa.py, city_scrapers/spiders/chi_ssa_19.py, city_scrapers/spiders/chi_ssa_24.py, city_scrapers/spiders/chi_ssa_43.py, city_scrapers/spiders/chi_ssa_54.py, tests/files/chi_ssa_19.html, tests/files/chi_ssa_24.html, tests/files/chi_ssa_43.html, tests/files/chi_ssa_54.html, tests/test_chi_ssa_19.py, tests/test_chi_ssa_24.py, tests/test_chi_ssa_43.py, tests/test_chi_ssa_54.py
Add mixin and scrapers for Rogers Park SSAs
=> Add Rogers Park SSA scrapers

city_scrapers/spiders/cook_medical_examiner.py, tests/test_cook_medical_examiner.py
Fixes scraper to handle cancellations, simplifies date parsing
=> Fix cook_medical_examiner

tests/utils.py
=> Test utils fix

city_scrapers/spiders/chi_ssa_2.py, tests/files/chi_ssa_2.html, tests/test_chi_ssa_2.py
This is my first spider for issue #571. Let me know if there's anything I need to fix!
=> SSA #2 spider

city_scrapers/spiders/il_lottery.py, tests/files/il_lottery.html, tests/test_il_lottery.py
This is my first spider for city-scrapers so I thought I'd check to see if I'm heading in the right general direction.
Currently, this spider only extracts meeting dates and agendas for **upcoming** meetings. 
Should I add the ability to scrape past meetings and agendas as well? I can refactor this to make it more similar to the ChiHousingAuthoritySpider, which has separate methods for scraping upcoming and past meetings.
=> 0798-spider-il_lottery

city_scrapers/spiders/wayne_mental_health_authority.py, tests/files/wayne_mental_health_authority.html, tests/files/wayne_mental_health_authority_docs.html, tests/test_wayne_mental_health_authority.py
=> Add wayne_mental_health_authority

city_scrapers/spiders/il_police_professionalism.py, tests/files/il_police_professionalism.html, tests/test_il_police_professionalism.py
This is my first commit. Just wanted to make sure I did everything right till this point so that I can start working on the parse methods. Any advice is welcome. Thanks!
=> Created bare bones spider for il_police_professionalism

city_scrapers/spiders/il_board_of_examiners.py, tests/files/il_board_of_examiners.html, tests/test_il_board_of_examiners.py
Created a barebone spider. Wanted to make sure that everything is good.  advice is welcome. Thanks.!!
=> Created barebones spider for il_board_of_examiners

city_scrapers/spiders/chi_midway_noise.py, tests/files/chi_midway_noise.html, tests/test_chi_midway_noise.py
Hi! I believe this spider and it's tests are finished. This is my first ever PR, so please help me learn if I've done something incorrectly or even just sub-optimally! In addition to the spider and tests, I did complete the yapf/isort/flake8 and pytest steps as specified in the instructions at https://cityscrapers.org/docs/development/.
One note about the code - yapf expanded what had been a fairly compact set of definitions for the links in the test_links() test into a much larger block of code - it went from about 100 lines to closer to 500 lines. I find that section to be much less clear and clean-looking as a result of the yapf changes.
I'm happy to re-work anything that you're unhappy with - looking forward to your feedback!
=> 0670 spider chi midway noise

docs/_docs/04-development.md
=> Update documentation on best practices

.travis.yml, requirements.txt
Attempt to fix the issue of Python 3.5 builds occasionally failing
=> Update Travis CI build

city_scrapers/spiders/il_investment_policy.py, tests/files/il_investment_policy.html, tests/test_il_investment_policy.py
Here's a shot at #803. Let me know how it looks.
=> 0803 spider il investment policy

city_scrapers/spiders/wayne_local_emergency_planning.py, tests/files/wayne_local_emergency_planning.html, tests/test_wayne_local_emergency_planning.py
This is my first pull request!
=> 0853 spider wayne county lepc

city_scrapers/spiders/chi_ssa_61.py
Teeny change, but an important one, I suppose (especially for reducing confusion). :-P
=> Fix typo in agency name (#843)

city_scrapers/spiders/cook_county_board_ethics.py, tests/files/cook_county_board_ethics_event.html, tests/test_cook_county_board_ethics.py
=> 0656-spider-cook_county_board_ethics

tests/files/cook_county_event.html, tests/test_cook_county.py
Please review and let me know if you want any (other) changes
=> 0890-improve test_cook_county (freezegun, file_response)

tests/test_cook_board_ethics.py
Alright. I think this should do it, please review
=> 0891-improve_test_cook_board_ethics

city_scrapers/spiders/il_arts_council.py, tests/files/il_arts_council.html, tests/test_il_arts_council.py
PR for https://github.com/City-Bureau/city-scrapers/issues/912. 
I did have a question, how should I handle `cancelled` meetings? The [website](http://www.arts.illinois.gov/about-iac/governance/council-meetings) uses the location field to indicate whether a meeting is canceled or not but I wasn't sure if there was a different field I should use on the meeting object to indicate that.
=> Issue 912: il_arts_council

city_scrapers/spiders/il_capital_development.py, tests/files/il_capital_development.html, tests/test_il_capital_development.py
@pjsier - Everything should be g2g here.
=> 0913: Spider for issue #913

city_scrapers/spiders/chi_ssa_28.py, tests/files/chi_ssa_28.html, tests/test_chi_ssa_28.py
=> 0906: Spider for issue #906

city_scrapers/spiders/chi_ssa_72.py, tests/files/chi_ssa_72.html, tests/test_chi_ssa_72.py
Addresses https://github.com/City-Bureau/city-scrapers/issues/846
=> 0846 spider chi_ssa_72

city_scrapers/spiders/chi_standards_tests.py, tests/files/chi_standards_tests.html, tests/test_chi_standards_tests.py
Issue #873 - Chicago Committee on Standards and Tests 
Added parser and tests for website stated in issue.
=> Add 0873 chi_standards_tests

.deploy.sh, .github/workflows/ci.yml, .github/workflows/cron.yml, Pipfile, Pipfile.lock, docs/_docs/04-development.md, docs/_docs/setuphelp.md
=> Update deps, CI, cleanup docs

city_scrapers/spiders/chi_ssa_48.py, tests/files/chi_ssa_48.html, tests/test_chi_ssa_48.py
**Issue:**  #569 
No questions.
=> Completed spider with tests.

city_scrapers/spiders/il_aging_advisory_council.py, tests/files/il_aging_advisory_council.html, tests/test_il_aging_advisory_council.py
**Issue:** #680 
- [X ] Tests are implemented
- [ X] All tests are passing
- [ X] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [X ] Style checks are passing
- [ X] Code comments from template removed
=> 0680 spider il aging advisory council

city_scrapers/spiders/chi_ssa_18.py, tests/files/chi_ssa_18.html, tests/test_chi_ssa_18.py
**Issue:** #559 
- [X ] Tests are implemented
- [ X] All tests are passing
- [ X] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [ X] Style checks are passing
- [ X] Code comments from template removed
=> 0559 spider chi ssa 18

city_scrapers/spiders/chi_ssa_23.py, tests/files/chi_ssa_23.html, tests/test_chi_ssa_23.py
**Issue:** #562
First pull request and first time working with scrapy. I am interested to hear your opinion. First started with CSS selectors, the realized how much XPATH makes things easier.
I tried to keep the checks regarding the document links from getting too "nested". Currently there are no documents uploaded for the year 2020 it. I find it hard to guess with what HTML formatting will this be done (if they will leave the ordered list and add the href for a list element or if an extra H4 will be …
=> #562 Chicago Special Service Area #23

Pipfile.lock, city_scrapers/spiders/chi_ssa_18.py, setup.cfg
Updates Python dependencies, including a Scrapy major version upgrade
=> build: update Python deps

city_scrapers/spiders/cook_justice_advisory.py, tests/files/cook_justice_advisory.html, tests/files/cook_justice_advisory_details.html, tests/test_cook_justice_advisory.py
=> 0911 spider cook justice advisory

city_scrapers/spiders/cook_human_rights.py, tests/files/cook_human_rights.html, tests/files/cook_human_rights_file.html, tests/test_cook_human_rights.py
=> 0855 spider cook human rights

city_scrapers/spiders/chi_north_river_mental_health.py, tests/files/chi_north_river_mental_health_index.html, tests/files/chi_north_river_mental_health_minutes.html, tests/test_chi_north_river_mental_health.py
**Issue:** #772 
Hi!
Please review and let me know what you think
What needs to be modified right now? What needs to be changed/added next?
=> 0772-spider-chi_north_river_mental_health ready for review

city_scrapers/spiders/chi_ssa_8.py, tests/files/chi_ssa_8.html, tests/test_chi_ssa_8.py
=> 0879 Chicago Special Service Area

city_scrapers/spiders/chi_state_university.py, tests/files/chi_state_university.html, tests/test_chi_state_university.py
=> 0718 spider chicago state university

city_scrapers/spiders/il_sports_facilities_authority.py, tests/files/il_sports_facilities_authority.html, tests/test_il_sports_facilities_authority.py
**Issue:** #681
Split the meeting scraper into two parts - one for the past meetings and one for the next meeting (which has a different format from the past meetings). 
Due to the two different formats of meetings (past v. next), I had to create separate `_parse` methods for the next meeting. Let me know if this is unwanted
=> 0681 spider il sports facilities authority

city_scrapers/spiders/chi_ssa_52.py, tests/files/chi_ssa_52.html, tests/test_chi_ssa_52.py
**Issue:** #574 
So, i've run into two problems. The first one was when parsing the date, the months were written incorrectly. My solution was to have a list of months and check the ratio comparing the right month string versus the wrong month string, and if the ratio is above 0.5, the incorrect string is replace with the correct one in the list. And about the test, i …
=> 0574 spider chi ssa 52

city_scrapers/spiders/cook_pharmaceutical_disposal.py, tests/files/cook_pharmaceutical_disposal.html, tests/test_cook_pharmaceutical_disposal.py
**Issue:** #0854
The date format for past meetings has been inconsistent. I tried to find the dates without using the PDF files.
=> Add 0854-spide-cook-pharma

city_scrapers/spiders/chi_human_relations.py, city_scrapers/spiders/chi_landmark_commission.py, city_scrapers/spiders/chi_policeboard.py, city_scrapers/spiders/chi_ssa_17.py, city_scrapers/spiders/chi_ssa_27.py, city_scrapers/spiders/chi_ssa_5.py, city_scrapers/spiders/chi_ssa_62.py, city_scrapers/spiders/chi_ssa_73.py, city_scrapers/spiders/cook_pharmaceutical_disposal.py, city_scrapers/spiders/il_board_of_examiners.py, city_scrapers/spiders/il_elections.py, city_scrapers/spiders/il_sports_facilities_authority.py, tests/files/chi_landmark_commission.html, tests/test_chi_landmark_commission.py
=> Multiple scraper fixes

city_scrapers/spiders/chi_animal.py, city_scrapers/spiders/chi_boardofethics.py, city_scrapers/spiders/chi_development_fund.py, city_scrapers/spiders/chi_plan_commission.py, city_scrapers/spiders/chi_pubhealth.py, city_scrapers/spiders/chi_standards_tests.py, city_scrapers/spiders/cook_north_shore_mosquito.py, tests/files/chi_animal.html, tests/files/chi_boardofethics.html, tests/files/chi_development_fund.html, tests/files/chi_plan_commission.html, tests/files/chi_plan_commission_detail.html, tests/files/chi_pubhealth.html, tests/files/chi_standards_tests.html, tests/test_chi_animal.py, tests/test_chi_boardofethics.py, tests/test_chi_development_fund.py, tests/test_chi_plan_commission.py, tests/test_chi_pubhealth.py, tests/test_chi_standards_tests.py
Fixes a few more scrapers that were silently failing
=> Fix additional scrapers

city_scrapers/spiders/chi_parks.py, city_scrapers/spiders/chi_ssa_4.py, city_scrapers/spiders/chi_ssa_73.py, city_scrapers/spiders/il_port_district.py, city_scrapers/spiders/il_sports_facilities_authority.py, tests/files/il_sports_facilities_authority.html, tests/test_chi_parks.py, tests/test_il_sports_facilities_authority.py
=> Scraper fixes

city_scrapers/spiders/il_health_facilities.py, tests/files/il_health_facilities.html, tests/files/il_health_facilities_helper.html, tests/test_il_health_facilities.py
=> Contains spider for Illinois Health Facilities meetings for issue 1001

city_scrapers/spiders/chi_pubhealth.py, tests/files/chi_pubhealth_2024.html, tests/test_chi_pubhealth.py
Fixes our Chicago Department of Public Health spider (aka. `chi_pubhealth`).
The spider broke due to changes on the pages it's targeting. The changes in this PR ensure the scraper runs without error.
After installing the project using `pipenv`:
1. Activate the virtual environment:
```
pipenv shell
```
2. Run the spider:
```
scrapy crawl chi_pubhealth -O test_output.csv
```
3. Monitor the stdout and ensure that the crawl proceeds without raising any errors. Pay attention to the final status report from scrapy.
4. Inspect `test_output.csv` to ensure the data looks valid. I suggest opening a few of the URLs under the source column of test_output.csv and comparing the data for the row with what you see on the page.
=> 🕷️ Fix spider: Chicago Department of Public Health
