City-Bureau/city-scrapers

.travis.yml, docs/contribute-a-spider.md, tasks.py
I've added an invoke task that runs the tests and all style checkers in order to help developers follow the style guidelines used by the project. This should also help prevent the situation where a developer runs the tests locally and sees them pass only to have CI fail due to a style issue.
If there is a better name than `runtests`, I'm all ears!
=> Add runtests invoke task

tasks.py
Hopefully fixes #62 by attempting to load the `pty` module to see if we're running on an OS that supports it.
=> Don't attempt to use pty=true if pty isn't available.

docs/contribute-a-spider.md, docs/event_schema.md
I added a description of our event schema to the docs. We already have it in the comments from the generator and it is available on the [Open Civic Data site](http://docs.opencivicdata.org/en/latest/data/event.html), but I thought it made sense to have it in our docs for ease of access.
I also added some words about the dev process and opening a pull request. It's a start, and I imagine we'll continue to develop that content over time.
=> Document event schema and writing tests

docs/contribute-a-spider.md, docs/installation.md
- using the `-s` flag with `genspider` to download html files for testing
- setup without virtualenvwrapper (maybe I'm the only one who does this? I like it as a reference since I delete my local repo from time to time.)
=> added more to the docs

tasks.py
Without this patch, the `genspider` function recommended by the documentation on creating a new spider will fail when it reaches line 58 and tries to run `_gen_html` without a session argument.
The error looks like this:
```python
Traceback (most recent call last):
File "/home/palewire/.virtualenvs/documenters-aggregator/bin/invoke", line 11, in <module>
sys.exit(program.run())
File "/home/palewire/.virtualenvs/documenters-aggregator/lib/python3.5/site-packages/invoke/program.py", line 294, in run
self.execute()
File "/home/palewire/.virtualenvs/documenters-aggregator/lib/python3.5/site-packages/invoke/program.py", line 409, in execute
executor.execute(*self.tasks)
File "/home/palewire/.virtualenvs/documenters-aggregator/lib/python3.5/site-packages/invoke/executor.py", line 129, in …
```
=> Added default session value to _gen_html function

documenters_aggregator/pipelines/__init__.py
The scrapy command is currently failing because the settings are failing to import the logging pipeline from a nested file. I've corrected that problem by introducing an import to the file's parent module that will line up with the path provided in the settings.
Here's the bug I saw that sent me down this route
```python
$ scrapy crawl accc
no pupa_settings on path, using defaults
2017-10-14 13:47:18 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: documenters_aggregator)
2017-10-14 13:47:18 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'documenters_aggregator.spiders', 'CLOSESPIDER_ERRORCOUNT': 5, 'COOKIES_ENABLED': False, 'COMMANDS_MODULE': 'documenters_aggregator.commands', 'USER_AGENT': 'Documenters Aggregator [development mode]. Learn more and say hello at …
```
=> Add pipelines import to fix scrapy bug

documenters_aggregator/spiders/pbcc.py, tests/files/pbcc.html, tests/test_pbcc.py
Closes #71. This is ready for review, but I wanted to flag a couple things I wasn't sure about because  they seemed different than most of the other scrapers.
* I used the few PBCC event types for `classification`, but I could also see those getting moved to `name` alone
* The location information is all over the place in terms of structure and text content, so I left it off since it has the URL included
* I used the `all_day` field events at Daley Plaza without a start time, but not sure if those should just be listed as starting at midnight
* Most events had no description, but the advertisements for bids had full pages ([one example](http://www.pbcchicago.com/content/working/opening_display.asp?BID_ID=502)). Instead of trying to pick which part of the page to include I left …
=> Spider: PBCC

.gitignore, requirements.txt, tasks.py
Was seeing an issue with our linters parsing a `src` directory that I think arose from these changes: 1fd9c7a. This PR is to add [Flake8](http://flake8.pycqa.org/), which has PEP 8 and pyflakes linters built in, while also allowing us to ignore directories we don't need to lint.
=> Use Flake8

documenters_aggregator/spiders/pbcc.py, tests/test_pbcc.py
Should fix #166, but not completely sure. Looks like I missed the part of `event-schema.md` that says coordinates should be a string. If there are any tests I can add for Airtable let me know
=> Convert PBCC coordinates to string

tests/test_pbcc.py
Fixes the error with the PBCC scraper tests pointed out in #171. The starting date is set in the scraper with `datetime.now()`, which works when it's run normally, but caused an error for the sample data generated in October because it tried to create November 31 based on the HTML file. Manually setting it to that time now so the tests pass
=> Fix PBCC tests

documenters_aggregator/settings.py
Fixes #178.
Specifically, it's worth noting that the debug messages were being caused by `from deploy import ecs` in `tasks.py`, so if we wanted to be more surgical about this and put something specific in `deploy/ecs.py` then I can take another look.
=> Raise base logging level

deploy/prod_settings.py.example, documenters_aggregator/pipelines/airtable.py, documenters_aggregator/spider.py, documenters_aggregator/spiders/chi_animal.py, documenters_aggregator/spiders/chi_buildings.py, documenters_aggregator/spiders/chi_city_college.py, documenters_aggregator/spiders/chi_parks.py, documenters_aggregator/spiders/chi_policeboard.py, documenters_aggregator/spiders/chi_schools.py, documenters_aggregator/spiders/cityclerk.py, requirements.txt, tests/test_chi_animal.py, tests/test_chi_buildings.py, tests/test_chi_city_college.py, tests/test_chi_parks.py, tests/test_chi_policeboard.py, tests/test_chi_schools.py, tests/test_cityclerk.py
This pull request changes the way we generate events ids to a new scheme that is more human- and machine-readable. (We should always treat ids as opaque, and I thought about hashing the result to enforce this, but that seemed overbearing at this point).
I want to get this locked down so that we can start using the system. We can easily make a change to any of the other values for an event later on, but getting the identifiers right needs to be done now as changing their format later will be extremely painful.
Most of the spiders are using their own heuristic to come up with an event identifier (usually using the date and sometimes the event name), as there is often not a publicly-visible ID for each event.
This set of patches will (when complete) update all spiders to use IDs in the …
=> Standardize ids

documenters_aggregator/spiders/chi_transit.py, tests/files/chi_transit.html, tests/test_chi_transit.py
Adding a spider for the Chicago Transit Authority board. It's mostly straightforward, but there's one part I have a question on.
On the [events page](http://www.transitchicago.com/agendaminute/default.aspx?F_OrderBy=MeetingDate+DESC), one type of meeting's start time is consistently marked "Immediately following Cmt Strategic Planning & Svs". I'm just setting the date on those and leaving the time at midnight, but would it be better to add a time an hour or so after the previous meeting?
=> Add CTA board spider

documenters_aggregator/spiders/chi_transit.py, tests/test_chi_transit.py
Fixes #204. It wasn't checking for null results from `item_start`, but this should resolve it
=> Add null check to chi_transit, update for event schema

documenters_aggregator/pipelines/airtable.py
Fixes #209. Airtable should show "N/A" instead of "n/a" and location name strings should be title-cased so that "6th district police station" becomes 6th District Police Station".
I tried using the Inflector library initially, but for the "6th district police station" example it returns "6Th District Police Station". Looking at the source of their `titleize` method, it's mostly just calling Python's `title()` which converts ordinal number string like "6th" to "6Th". Calling `capitalize()` manually isn't too much more complex and avoids that issue
=> Capitalize location_name, N/A in Airtable

tasks.py
Fixes #243.
Now we only attempt to discover tests within our `tests` directory.
=> Specify a specific directory to look inside of for tests.

documenters_aggregator/spiders/chi_buildings.py, tests/files/chi_buildings.html, tests/files/chi_buildings.json, tests/test_chi_buildings.py
Closes #252. A more detailed description and location information aren't included in the JSON endpoint, so the spider scrapes those pages if they aren't board meetings (which generally don't have any more info)
=> Rebuild PBCC spider for updated site

deploy/aws_setup.py, deploy/scraperScheduler/index.js
When this is merged, the script that chooses which spider to run will be updated on every deploy.
It is currently setup to run every 30 minutes. When we have more than 48 spiders, we'll need to reassess this to avoid spiders from being skipped.
=> Auto deploy lambda scheduler

documenters_aggregator/spiders/chi_pubhealth.py, tests/files/chi_pubhealth.html, tests/test_chi_pubhealth.py
Use the 2018 link, adapt `xpaths` to new page, simplify date parsing. 
A couple of Qs:
- I'm skipping events for which a date can't be parsed. Judging by [the placeholder links](https://www.cityofchicago.org/city/en/depts/cdph/supp_info/boh/2018-board-of-health-meetings.html), this should work through this year. However, is this the right thing to do? For example, if they misspell February next year, this spider would silently pass over that event. 
- I think this is right from the text of #258 ("scrape that instead"), but just to confirm: We no longer need to scrape events from 2017?
Closes #258
=> Repair Chicago Dept of Public Health scraper

.gitignore, README.md, deploy/scrapers_status.py, deploy/scrapers_status_cfn.yml
Working on #265. Adds a CloudFormation template that creates the Lambda function and S3 bucket to store icons for each scraper's status. I tested it on my AWS account, and everything runs as expected from a test event (when the event-specific parts are commented out). We should be able to add a trigger from an ECS task state change to get it running, but I'm not sure where in the event object I can pull the scraper name
@jim let me know what you think, and if you have a sense of where we can get the scraper info
=> Create icon dashboard for scraper status

deploy/scrapers_status.py
Should fix some issues with #265. Sets 'Cache-Control' header for the SVGs on S3
=> Add no-cache to SVG icon headers

docs/03_contribute.md, documenters_aggregator/settings.py, documenters_aggregator/spiders/chi_school_actions.py, documenters_aggregator/spiders/metra_board.py, templates/spider.tmpl, tests/files/testspider.py.example, travis/travis_settings.py
I noticed the spider template was pointing to the gitbooks version of the docs, which appear to be broken. It looks like we switched to GH pages for docs, so I updated all the URLS to be current.
=> updates doc links in  code and template to point to GH pages

deploy/city-scrapers-status/scrapers_status.py
Closes #301. The code for getting the scraper name was pulling the version number instead. This fixes it, and it's currently running in the Lambda. It also looks like GitHub is handling the `no-cache` header the way it should, so the dashboard should work as intended now. This also uses `timedelta` to get the time in CST rather than importing an external library to keep the setup simple
=> Fix getting scraper name

.gitattributes
This is a really minor, superficial thing so feel free to ignore it, but it's been bugging me that the repo shows up as HTML on GitHub even though the actual code is Python. This adds a `.gitattributes` file to ignore all of the test HTML files in the language stats by [treating them as generated code](https://github.com/github/linguist#generated-code). It doesn't show up as fixed when you view my branch because it looks like the calculations are based on the main/master branch https://help.github.com/articles/about-repository-languages/
=> Ignore test HTML in GitHub repo language stats

documenters_aggregator/spiders/il_pubhealth.py, requirements.txt, tests/test_il_pubhealth.py
This change uses the [usaddress](https://github.com/datamade/usaddress) to make a conservative guess at the correct address in the free form description.
This is a first pass fix for https://github.com/City-Bureau/city-scrapers/issues/201.
=> Use usaddress to make conservative guess at address

templates/spider.tmpl, tests/files/testspider.py.example
Addresses issue #310, fix typo in spider.tmpl, add a new line at end of doc.
=> Issue 310 - fix typo in spider.tmpl

city_scrapers/exporters.py, city_scrapers/pipelines/__init__.py, city_scrapers/pipelines/airtable.py, city_scrapers/pipelines/item.py, deploy/prod_settings.py
Adds an initial feed export for writing newline-delimited JSON to S3 for each scraper after it's run in production. We'll likely have a different setup for writing files to S3 for the actual platform, but this is a decent placeholder for running the [public events viewer](https://github.com/City-Bureau/city-scrapers-events)
Also closes #333 by adding a new `CityScrapersItemPipeline` that splits out the `agency_name` assignment from the `AirtablePipeline`
=> Add S3 JSONLines feed export

city_scrapers/spider.py, deploy/city_scrapers_cfn.yml, deploy/prod_settings.py
The export and pipeline from #332 are working, but initially they weren't getting uploaded to S3 because the job role didn't have S3 access. This is already updated on AWS, so if I don't hear anything I'll merge this tomorrow morning. It also adds some params to the `__init__` function so that we have more control of the S3 key generation
=> Fix Batch S3 access in cfn template

docs/02_installation.md
@o-stovicek pointed out a permissions error while setting up for Codeanywhere, and I realized that we are using the ssh syntax for cloning the project. If we want to keep SSH, we should include instructions for generating a keypair
=> change git clone to https url

README.md, city_scrapers/commands/list.py, city_scrapers/pipelines/item.py, deploy/post_build.sh, travis/debug_validations.sh, travis/validate_spiders.sh
Fixes #405
* It looks like the shell scripts still need the `PYTHONPATH` modifying, so that's added back
* Check for either `long_name` or `agency_id` in the item pipeline so we have more time for that migration
* Check if the branch in CodeBuild ends in `master` so that `refs/origin/master` is also matched for deployment
* Update the README with some spiders that had been missed
If no one has any issues with this I'll merge it later today since some spiders are currently failing
=> Fix deployment-related issues

city_scrapers/exporters.py, city_scrapers/pipelines/__init__.py, city_scrapers/pipelines/s3_item.py, city_scrapers/settings/base.py, city_scrapers/settings/prod.py
In addition to the feed export of each run of a given spider, write each individual meeting to S3, only updating keys that either don't exist or have changed. This is for the documenters platform, which adds any updated keys in this bucket to an SQS queue.
If the tests pass on this I'll merge it later today if no one has any issues with it
=> Add pipeline for writing events to S3

tests/test_chi_school_community_action_council.py
Some of the chi_school_community_action_council tests started failing because it's no longer June 2018. I used freeze_time so that these tests will always act as if it's June 2018.
=> fix time sensitive CAC tests

city_scrapers/spiders/chi_buildings.py, tests/test_chi_buildings.py
This is updated to pull only board meetings, audit committee meetings, and admin opp committee meetings. I saw the note about parsing descriptions but it appears that that functionality is built in, could you give me more context on that? @r-wei @diaholliday
=> Chi Buildings Revision #370

city_scrapers/pipelines/__init__.py, city_scrapers/settings/prod.py
Fixes the logging errors in #432. Because the S3 item pipeline was getting imported from the `pipelines` `__init__` file, all Scrapy environments were trying to load `boto3` and logging errors when it failed to find AWS credentials set up locally.
I split out the import so that it's only included in the production environment, and now I don't see any `boto3` logs locally when running spiders in development (I saw logs for it before, but they didn't throw errors)
=> Change S3 item pipeline import for logging

city_scrapers/spiders/chi_police.py, city_scrapers/spiders/chi_school_actions.py, tests/test_chi_police.py, tests/test_chi_school_actions.py
Closes #454. Adds "Chicago, IL" by default to the end of the CAPS and school action spiders since they don't include city or state information. Will merge tonight or tomorrow if no one has any issues
=> Add 'Chicago, IL' to spider addresses

.gitignore, deploy/aws_setup.py, deploy/city_scrapers_cfn.yml
Batch isn't returning every active job in an intuitive way, so this still deregisters active jobs but then attempts to schedule every job name so that we can make sure all of the scrapers run. Also adds `.pytest_cache` to the `.gitignore` which only popped up for me recently.
This is already running on the Lambda, so I'll merge this tomorrow if no one has any objections
=> Update job definitions and scheduling

city_scrapers/pipelines/item.py, city_scrapers/spiders/chi_library.py, city_scrapers/utils.py
Uses Python's `functools` library to create a decorator that will catch, report to Sentry and re-raise any exception that surfaces in the wrapped method.
Adding screenshots below to demonstrate what data shows in Sentry.
Please let me know if I should add the code to put the decorator on all the pipelines.
^ shown stack trace is from the correct location and shows the pipeline name.
^ extra data includes all the inputs to the wrapped function (in this case the item being passed to the pipeline)
=> Add decorator to catch pipeline errors

city_scrapers/spiders/chi_library.py
`chi_library` spider was only failing in production because the `__init__` method of the `Spider` parent class wasn't being called, so the Feed URI wasn't able to be populated. Adds a call to `super()` in `__init__`
=> Fix Chicago Library initializer

city_scrapers/pipelines/item.py, city_scrapers/spider.py, city_scrapers/spiders/chi_animal.py, city_scrapers/spiders/il_metra_board.py, tests/test_pipeline_localexport.py
* Removes `_naive_datetime_to_tz` since it's not longer needed
* Adds `_clean_name` to base spider which removes strings mentioning cancellation or rescheduling from a meeting's name so that the original ID isn't changed
* Updates the item pipeline to apply these changes to each item so spiders don't have to be changed
=> Clean up cancellation strings in item names

city_scrapers/spiders/chi_low_income_housing_trust_fund.py, tests/test_chi_low_income_housing_trust_fund.py
Same day meetings were being cancelled in `chi_low_income_housing_trust_fund` because the selector wasn't looking for events under the selector `.current-day`. That's added here, and the spider is updated to use the `city_scrapers_core` setup
=> Fix cancellations, update Low Income Housing Trust

Pipfile.lock, city_scrapers/spiders/chi_animal.py, city_scrapers/spiders/chi_low_income_housing_trust_fund.py, city_scrapers/spiders/mi_belle_isle.py, tests/test_chi_animal.py, tests/test_cook_water.py, tests/test_det_eight_mile_woodward_corridor_improvement_authority.py, tests/test_det_entertainment_commission.py, tests/test_det_library_commission.py, tests/test_det_local_development_finance_authority.py, tests/test_det_next_michigan_development_corporation.py, tests/test_det_wrecking_examiners.py, tests/test_det_zoning_appeals.py, tests/test_mi_belle_isle.py, tests/test_wayne_election_commission.py
- Updates `city-scrapers-core` to 0.2.2
- Fixes `chi_animal` and `mi_belle_isle` and updates them to use `Meeting` items
- Fixes an issue in `chi_low_income_housing_trust_fund` where it was attempting to scrape empty URLs
=> Fix several broken scrapers, update core version

.travis.yml
We aren't logging anything anymore since even a small amount of logs would go over the Travis limits with all the pages we're scraping, but because of this we're hitting Travis's output-based timeout.
This adds `travis_wait` to the `scrapy runall` command as the [recommended way to get around this issue](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)
=> Add travis_wait to runall script

.deploy.sh, .travis.yml
It looks like `travis_wait` isn't supported in the `deploy` step, so using a custom script instead
=> Fix Travis CI deploy timeout

city_scrapers/spiders/chi_buildings.py, city_scrapers/spiders/chi_community_development.py, city_scrapers/spiders/chi_low_income_housing_trust_fund.py, city_scrapers/spiders/chi_plan_commission.py, city_scrapers/spiders/chi_policeboard.py, city_scrapers/spiders/il_metra_board.py, tests/test_chi_animal.py, tests/test_chi_plan_commission.py, tests/test_chi_policeboard.py
Mostly updates any cityofchicago.org URLs to be chicago.gov and removes an unneeded robots.txt override
=> Update redirecting URLs

CONTRIBUTING.md
Hello!
I'm a new comer interested in working on this project. As I was looking around at how to get started, I noticed that it appeared that each of the scrapers was built from an initial template file. I couldn't find any information about creating a new scraper in CONTRIBUTING.md, which was frustrating. It wasn't until I saw this [link](https://cityscrapers.org/docs/development/#contribute) to the contribution guide that I was able see the steps for creating a new scraper from template. I'm not sure how it would fit in with the current CONTRIBUTING.md file, but it might be nice if these steps or a link to this guide could be included. 
Thanks
=> Adding link to technical guide to CONTRIBUTING.md

Pipfile, Pipfile.lock
Allowing prereleases installed a breaking version of `azure-storage-blob`, and since we don't need it here this disables it and updates `Pipfile.lock`
=> Don't allow prereleases

Pipfile.lock
Fix issue where `pyparsing` release 2.4.1 was removed from PyPi
=> Fix issue with pyparsing release

city_scrapers/spiders/wayne_land_bank.py, tests/files/wayne_land_bank.html, tests/test_wayne_land_bank.py
This pull request adds the wayne_land_bank spider, the test file of that spider and target web page as an HTML file. 
-  To access the Board of Directors tab on the following page: https://public-wclb.epropertyplus.com/landmgmtpub/app/base/customPage we have to start with POST request.
- The desired data was included in `<script>` tags, thus to extract the data, the `re` regular expressions were used.
- The target site seems to be under the development, in the future the spider might require update if the website layer was changed or new information were added.
=> Add wayne_land_bank spider

city_scrapers/spiders/chi_ssa_32.py, tests/files/chi_ssa_32.json, tests/test_chi_ssa_32.py
Spider for `Chicago Special Service Area #32 Auburn Gresham` (chi_ssa_32) which uses Google Calendar to track its meetings. Resolves #907.
Most of this code was taken from PR #915 that created a spider for `SSA #69` which uses the same Google Calendar source.
Thanks @pjsier for your help pointing me to the above PR when I was almost giving up with this spider.
=> Spider for issue #907

.github/workflows/ci.yml, .github/workflows/cron.yml, Pipfile, Pipfile.lock, docs/_docs/04-development.md
**Issue:** #957
Closes #957. Feel free to comment here or on the issue if anyone has concerns with dropping Python 3.5
=> Drop Python 3.5, update Pipenv

docs/_docs/setuphelp.md
I found a link in one of the docs that seemed corrupted: it seemed like it was supposed to lead to someone's blog but I think the address has since changed hands. I found another link that I believe fulfills the same purpose, which is to show an example of using automatic linting in setting up Sublime.
@pjsier it might be good to check out the new link https://janikarhunen.fi/three-steps-to-lint-python-3-6-in-sublime-text just to make sure you approve of the content, and let me know if it doesn't work for the purposes of these docs.
=> Swap broken link for new Sublime linter link

.github/workflows/archive.yml, .github/workflows/ci.yml, .github/workflows/cron.yml, Pipfile, Pipfile.lock, city_scrapers/spiders/chi_citycouncil.py, city_scrapers/spiders/chi_midway_noise.py, tests/files/chi_citycouncil.json, tests/test_chi_citycouncil.py
- Some packages in `Pipfile.lock` cannot be installed because they require Python version 3.8, while we use a Python 3.7 environment for running daily archiving and cron tasks. Additionally, our CI environment is set up with Python 3.9. Therefore, we have updated the Python version for these three workflows to 3.9 and adjusted the package versions in `Pipfile.lock` to ensure compatibility with this Python version.
- The installed pypi `scrapy-sentry` version is deprecated so we use the customized version at https://github.com/City-Bureau/scrapy-sentry/releases/tag/v1.
- Update spider `ChiCitycouncilSpider` by assigning API endpoint to class attribute `ChiCitycouncilSpider.start_urls`.
- Fix failed tests.
=> [c] Fix cron tasks

Pipfile, Pipfile.lock
Deletes [pypiwin32](https://github.com/Googulator/pypiwin32) from our pipfile and rebuilds our lock file, which appears to solve an issue with our dependencies that was causing our CI github workflow to [fail](https://github.com/City-Bureau/city-scrapers/actions/runs/7019251871/job/19683189437) when triggered.
I recently opened a [PR](https://github.com/City-Bureau/city-scrapers/pull/1053) (my first for this repo) with relatively small changes and immediately discovered our CI github action was failing. The failure appeared totally unrelated to my changes. The error was occurring just as Pipenv attempted to install packages:
```
Successfully created virtual environment!
Virtualenv location: /home/runner/work/city-scrapers/city-scrapers/.venv
Installing dependencies from Pipfile.lock …
```
=> ⛔  Remove pypiwin32 package

city_scrapers/spiders/il_commerce.py, tests/files/il_commerce.html, tests/files/il_commerce_detail.html, tests/test_il_commerce.py
Fixes our Illinois Commerce Commission spider (aka. `il_commerce`), which broke due to URL and HTML changes on the target webpage.
We want working scrapers, of course 🤖  The changes in this PR include targeting a slightly different URL and using new CSS selectors. 
After installing the project using `pipenv` (see Readme):
1. Run:
```
scrapy crawl il_commerce -O test_output.csv
```
2. Monitor the stdout and ensure that the crawl proceeds without raising any errors. Pay attention to the final status report from scrapy.
3. Inspect `test_output.csv` to ensure the data looks valid. I suggest taking a cursory look at the [target webpage](https://www.icc.illinois.gov/meetings?dts=32&scm=True&sps=True&sh=True&sjc=True&ssh=False&smceb=True) and clicking through to a few of the meeting detail pages …
=> 🕷️ Fix spider: Illinois Commerce Commission

.github/workflows/cron.yml
Adds an extra step to our scheduled scrape workflow (named "cron") that will automatically create a dummy commit in the repo if the last commit to the repo was 50 days ago.
We recently discovered that workflows in a number of our city-scraper repos were disabled by Github because there had been no commits in 60 days. Adding this extra step to our workflow using a third party Github action called [keepalive-workflow](https://github.com/marketplace/actions/keepalive-workflow) should prevent that.
I manually triggered our `cron` workflow from this branch (`keepalive`) in order to ensure the workflow executed and didn't causing unexpected problems. Here's the [output](https://github.com/City-Bureau/city-scrapers/actions/runs/7451651828/job/20273217175). If you wish to replicate, do the …
=> ⚙️ Prevent github workflow deactivation

Pipfile, Pipfile.lock, city_scrapers/settings/prod.py, city_scrapers/spiders/chi_ssa_34.py
Replaces the [scrapy-sentry](https://github.com/llonchj/scrapy-sentry) package with [scrapy-sentry-errors](https://github.com/City-Bureau/scrapy-sentry-errors). It also:
- requires python 3.9 in our Pipfile.
- rebuilds our lock file
- makes a slight styling tweak to a spider because our version of black was bumped slightly during the pipfile reinstallation.
`scrapy-sentry` needed to be replaced in this repo because it hasn't been maintained and appears to be causing strange dependency conflicts in a number of our city-scraper repos. `scrapy-sentry-errors` is our new, custom-built package for error monitoring. It functions virtually identically but uses newer python packaging practices and features key dependency upgrades.
n/a
n/a
=> 👾 Integrate scrapy-sentry-errors

city_scrapers/spiders/chi_human_relations.py, tests/files/chi_human_relations.html, tests/test_chi_human_relations.py
Fixes our Chicago Commission on Human Relations spider (aka. `chi_human_relations`).
The spider broke due to changes on the pages it's targeting. The changes in this PR ensure the scraper runs without error.
After installing the project using `pipenv`:
1. Activate the virtual environment:
```
pipenv shell
```
2. Run the spider:
```
scrapy crawl chi_human_relations -O test_output.csv
```
3. Monitor the stdout and ensure that the crawl proceeds without raising any errors. Pay attention to the final status report from scrapy.
4. Inspect `test_output.csv` to ensure the data looks valid. I suggest opening a few of the URLs under the source column of test_output.csv and comparing the data for the row with what you see on the page.
=> 🕷️ Fix spider: Chicago Commission on Human Relations
